import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import "@/app/globals.css";

import { Albert_Sans } from "next/font/google";

const albertSans = Albert_Sans({
  subsets: ['latin']
});

import Logo from "@/components/Misc/Logo";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={albertSans.className}>
          <div className="bg-[#fff] w-full h-[80px] flex flex-row text-black items-center border-b gap-2 px-4">
              <div className="border-r-2 pr-6">
                  <Logo/>
              </div>
          </div>
          {children}
      </body>
    </html>
  );
}
